package com.industrial.mdm.common.exception;

public enum ErrorCode {
    INVALID_REQUEST,
    INVALID_CREDENTIALS,
    SMS_CODE_INVALID,
    SMS_CODE_EXPIRED,
    REFRESH_TOKEN_INVALID,
    DUPLICATE_ACCOUNT,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    STATE_CONFLICT,
    ENTERPRISE_PROFILE_INCOMPLETE,
    PRODUCT_PROFILE_INCOMPLETE,
    INTERNAL_ERROR
}
